spring:
  application:
    name: project-management-app
  profiles:
    default: local
  datasource:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.projectmanagementapp.domain.model
  configuration:
    map-underscore-to-camel-case: true

projectmanagementapp:
  cors:
    allowed-origins:
      - http://localhost:5173
